xout_log_file_name: "/home/justin/xout.csv"
debug_log_file_name: "/home/justin/log.csv" 
hybrid_network_file_name: "/home/justin/code/AUVSL_ROS/src/auvsl_dynamics/data/hybrid_net.mat"
learn_rate: .00001
load_from_file: 1
test_first: 1